# Generated by Django 5.1.4 on 2025-01-10 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('turn_on', 'Turn On'), ('turn_off', 'Turn Off'), ('adjust_brightness', 'Adjust Brightness'), ('change_color', 'Change Color'), ('set_temperature', 'Set Temperature')], max_length=20)),
                ('time', models.TimeField()),
                ('brightness', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='smartlight',
            name='brightness',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='smartlight',
            name='color',
            field=models.CharField(default='White', max_length=20),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='current_temperature',
            field=models.FloatField(default=22.0),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='target_temperature',
            field=models.FloatField(default=22.0),
        ),
    ]
